---
- hosts: all
  become: true
  vars:
     contents: "{{ lookup('env','DOCKER_TAG') | replace('\n', '')}}"
  tasks:
  - name: stop if we have old docker container
    command: docker stop AnsibleContainer
    ignore_errors: yes

  - name: remove stopped docker container
    command: docker rm AnsibleContainer
    ignore_errors: yes

  - name: remove current docker image
    command: docker rmi dileep95/ansibledeploy
    ignore_errors: yes

  - debug: msg={{ contents }} 
