---
- hosts: all
  become: true
  tasks:
  - name: stop if we have old docker container
    command: docker stop AnsibleContainer
    ignore_errors: yes

  - name: remove stopped docker container
    command: docker rm AnsibleContainer
    ignore_errors: yes

  - name: remove current docker image
    command: docker rmi dileep95/ansibledeploy
    ignore_errors: yes
   
  - name: test the tag
    command: echo "{{ lookup('env','DOCKER_TAG') }}"
    register: check
    
  - name: test the tag
    debug:
    register: check.stdout

  - name: creating docker image
    command: docker run -d -p 8050:8050 --name AnsibleContainer dileep95/ansibledeploy:"{{ lookup('env','DOCKER_TAG') }}"
